<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KRaVHyH' shared service.

return $this->privates['.service_locator.KRaVHyH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('transaction' => function (): \App\Entity\Transaction {
    return ($this->privates['.errored..service_locator.KRaVHyH.App\Entity\Transaction'] ?? $this->load('getTransactionService.php'));
}));
