<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.E_BR3jr' shared service.

return $this->privates['.service_locator.E_BR3jr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('transactions' => function (): \App\Repository\TransactionRepository {
    return ($this->privates['App\Repository\TransactionRepository'] ?? $this->load('getTransactionRepositoryService.php'));
}));
