<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\ApiExceptionSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/ApiExceptionSubscriber.php';

return $this->privates['App\EventListener\ApiExceptionSubscriber'] = new \App\EventListener\ApiExceptionSubscriber(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
