<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cron.resolver' shared service.

include_once $this->targetDirs[3].'/vendor/cron/cron-bundle/Cron/CommandBuilder.php';
include_once $this->targetDirs[3].'/vendor/cron/cron/src/Resolver/ResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/cron/cron-bundle/Cron/Resolver.php';

return $this->services['cron.resolver'] = new \Cron\CronBundle\Cron\Resolver(($this->services['cron.manager'] ?? $this->load('getCron_ManagerService.php')), new \Cron\CronBundle\Cron\CommandBuilder('dev'), ($this->targetDirs[3].'/src'));
