<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cron.manager' shared service.

include_once $this->targetDirs[3].'/vendor/cron/cron-bundle/Cron/Manager.php';

return $this->services['cron.manager'] = new \Cron\CronBundle\Cron\Manager(($this->services['doctrine'] ?? $this->getDoctrineService()));
