<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.lrGgCyW.App\Entity\Customer' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.lrGgCyW": it references class "App\\Entity\\Customer" but no such service exists.');
