<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cron.executor' shared service.

include_once $this->targetDirs[3].'/vendor/cron/cron/src/Executor/ExecutorInterface.php';
include_once $this->targetDirs[3].'/vendor/cron/cron/src/Executor/Executor.php';

return $this->services['cron.executor'] = new \Cron\Executor\Executor();
