<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Api\\TransactionController::delete' => function () {
    return ($this->privates['.service_locator.KRaVHyH'] ?? $this->load('get_ServiceLocator_KRaVHyHService.php'));
}, 'App\\Controller\\Api\\TransactionController::getOne' => function () {
    return ($this->privates['.service_locator.lrGgCyW'] ?? $this->load('get_ServiceLocator_LrGgCyWService.php'));
}, 'App\\Controller\\Api\\TransactionController::index' => function () {
    return ($this->privates['.service_locator.E_BR3jr'] ?? $this->load('get_ServiceLocator_EBR3jrService.php'));
}, 'App\\Controller\\Api\\TransactionController::update' => function () {
    return ($this->privates['.service_locator.KRaVHyH'] ?? $this->load('get_ServiceLocator_KRaVHyHService.php'));
}, 'App\\Controller\\LoginController::login' => function () {
    return ($this->privates['.service_locator.pa1MOE1'] ?? $this->load('get_ServiceLocator_Pa1MOE1Service.php'));
}, 'App\\Controller\\Api\\TransactionController:delete' => function () {
    return ($this->privates['.service_locator.KRaVHyH'] ?? $this->load('get_ServiceLocator_KRaVHyHService.php'));
}, 'App\\Controller\\Api\\TransactionController:getOne' => function () {
    return ($this->privates['.service_locator.lrGgCyW'] ?? $this->load('get_ServiceLocator_LrGgCyWService.php'));
}, 'App\\Controller\\Api\\TransactionController:index' => function () {
    return ($this->privates['.service_locator.E_BR3jr'] ?? $this->load('get_ServiceLocator_EBR3jrService.php'));
}, 'App\\Controller\\Api\\TransactionController:update' => function () {
    return ($this->privates['.service_locator.KRaVHyH'] ?? $this->load('get_ServiceLocator_KRaVHyHService.php'));
}, 'App\\Controller\\LoginController:login' => function () {
    return ($this->privates['.service_locator.pa1MOE1'] ?? $this->load('get_ServiceLocator_Pa1MOE1Service.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
